./Bin/Linux/Assignment1 --in Test\ Images/input/yoda.bmp --out Test\ Images/output/noise1.bmp --noisify 0
./Bin/Linux/Assignment1 --in Test\ Images/input/yoda.bmp --out Test\ Images/output/noise2.bmp --noisify .5
./Bin/Linux/Assignment1 --in Test\ Images/input/yoda.bmp --out Test\ Images/output/noise3.bmp --noisify 1
./Bin/Linux/Assignment1 --in Test\ Images/input/yoda.bmp --out Test\ Images/output/bright1.bmp --brighten .5
./Bin/Linux/Assignment1 --in Test\ Images/input/yoda.bmp --out Test\ Images/output/bright2.bmp --brighten 2
./Bin/Linux/Assignment1 --in Test\ Images/input/shrek.bmp --out Test\ Images/output/contrast.5.bmp --contrast .5
./Bin/Linux/Assignment1 --in Test\ Images/input/shrek.bmp --out Test\ Images/output/contrast1.bmp --contrast 1
./Bin/Linux/Assignment1 --in Test\ Images/input/shrek.bmp --out Test\ Images/output/contrast2.bmp --contrast 2
./Bin/Linux/Assignment1 --in Test\ Images/input/shrek.bmp --out Test\ Images/output/sat.5.bmp --saturate .5
./Bin/Linux/Assignment1 --in Test\ Images/input/shrek.bmp --out Test\ Images/output/sat1.bmp --saturate 1
./Bin/Linux/Assignment1 --in Test\ Images/input/shrek.bmp --out Test\ Images/output/sat2.bmp --saturate 2
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/quant1.bmp --quantize 1
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/quant2.bmp --quantize 2
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/quant4.bmp --quantize 4
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/oDither1.bmp --oDither2x2 1
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/oDither2.bmp --oDither2x2 2
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/oDither4.bmp --oDither2x2 4
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/fsDither1.bmp --fsDither 1
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/fsDither2.bmp --fsDither 2
./Bin/Linux/Assignment1 --in Test\ Images/input/ramp.bmp --out Test\ Images/output/fsDither4.bmp --fsDither 4
./Bin/Linux/Assignment1 --in Test\ Images/input/shrek.bmp --out Test\ Images/output/crop.bmp --crop 100 100 50 50
./Bin/Linux/Assignment1 --in Test\ Images/input/stripe.2.bmp --out Test\ Images/output/scaleNearest.7.bmp --scaleNearest .7
./Bin/Linux/Assignment1 --in Test\ Images/input/stripe.2.bmp --out Test\ Images/output/scaleNearest1.bmp --scaleNearest 1
./Bin/Linux/Assignment1 --in Test\ Images/input/stripe.2.bmp --out Test\ Images/output/scaleNearest1.3.bmp --scaleNearest 1.3
./Bin/Linux/Assignment1 --in Test\ Images/input/stripe.2.bmp --out Test\ Images/output/scaleBilinear.7.bmp --scaleBilinear  .7
./Bin/Linux/Assignment1 --in Test\ Images/input/stripe.2.bmp --out Test\ Images/output/scaleBilinear1.bmp --scaleBilinear  1
./Bin/Linux/Assignment1 --in Test\ Images/input/stripe.2.bmp --out Test\ Images/output/scaleBilinear1.3.bmp --scaleBilinear  1.3
